stages:
    - check
    - test
    - build

check-updated-tag:
    image: python:3
    stage: check
    rules:
        - if: $CI_COMMIT_TAG

    tags:
        - python

    before_script:
        - echo "installing yq"
        - python -m pip install pip --upgrade && python -m pip install yq==3.2.3
        - sudo apt-get update -y && sudo apt-get install jq -y

    script:
        - echo "ensuring version matches tag"
        - python -m tomlq --compact-output --raw-output '.tool.poetry.version' pyproject.toml | grep -q '$CI_COMMIT_TAG'

build-latest-docker-image:
    stage: build
    tags:
        - docker

    rules:
        - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

    before_script:
        - echo "logging in to registry:$CI_REGISTRY as $CI_REGISTRY_USER"
        - docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
        - echo "pulling most recent latest image for caching"
        - docker pull $CI_REGISTRY_IMAGE:latest || true

    script:
        - echo "building docker image latest version"
        - docker build --cache-from $CI_REGISTRY_IMAGE:latest --tag $CI_REGISTRY_IMAGE:latest --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA .
        - echo "pushing built images to GitLab repository"
        - docker push $CI_REGISTRY_IMAGE:latest
        - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA

build-stable-docker-image:
    stage: build
    tags:
        - docker

    rules:
        - if: $CI_COMMIT_TAG

    when: manual

    before_script:
        - echo "logging in to registry:$CI_REGISTRY as $CI_REGISTRY_USER"
        - docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
        - echo "pulling most recent stable image for caching"
        - docker pull $CI_REGISTRY_IMAGE:stable || true

    script:
        - echo "building docker image stable version:$CI_COMMIT_TAG"
        - docker build --cache-from $CI_REGISTRY_IMAGE:stable --tag $CI_REGISTRY_IMAGE:stable --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG .
        - echo "pushing built images to GitLab repository"
        - docker push $CI_REGISTRY_IMAGE:stable
        - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
        - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
