stages:
    - check
    - test
    - build

check-updated-tag:
    image: python:3
    stage: check
    rules:
        - if: $CI_COMMIT_TAG

    before_script:
        - echo "installing yq"
        - pip install yq==0.9.17
        - apt update -y && apt install jq=1.6-2.1 -y

    script:
        - echo "ensuring version matches tag"
        - tomlq --compact-output --raw-output '.tool.poetry.version' pyproject.toml | grep -q '$CI_COMMIT_TAG'

build-latest-docker-image:
    stage: build
    tags:
        - docker

    rules:
        - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

    before_script:
        - echo "logging in to registry:$CI_REGISTRY as $CI_REGISTRY_USER"
        - docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
        - echo "pulling most recent latest image for caching"
        - docker pull $CI_REGISTRY_IMAGE:latest || true
        - docker pull $CI_REGISTRY_IMAGE:migrator-latest || true

    script:
        - echo "building docker image latest version"
        - docker build --cache-from $CI_REGISTRY_IMAGE:latest --tag $CI_REGISTRY_IMAGE:latest --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA Dockerfile.serve
        - echo "building docker image migrator-latest version"
        - docker build --cache-from $CI_REGISTRY_IMAGE:migrator-latest --tag $CI_REGISTRY_IMAGE:migrator-latest --tag $CI_REGISTRY_IMAGE:migrator-$CI_COMMIT_SHA Dockerfile.migrate
        - echo "pushing built images to GitLab repository"
        - docker push $CI_REGISTRY_IMAGE:latest
        - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
        - docker push $CI_REGISTRY_IMAGE:migrator-latest
        - docker push $CI_REGISTRY_IMAGE:migrator-$CI_COMMIT_SHA

build-stable-docker-image:
    stage: build
    tags:
        - docker

    rules:
        - if: $CI_COMMIT_TAG

    when: manual

    before_script:
        - echo "logging in to registry:$CI_REGISTRY as $CI_REGISTRY_USER"
        - docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
        - echo "pulling most recent stable image for caching"
        - docker pull $CI_REGISTRY_IMAGE:stable || true
        - docker pull $CI_REGISTRY_IMAGE:migrator-stable || true

    script:
        - echo "building docker image stable version:$CI_COMMIT_TAG"
        - docker build --cache-from $CI_REGISTRY_IMAGE:stable --tag $CI_REGISTRY_IMAGE:stable --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG -f Dockerfile.serve .
        - docker build --cache-from $CI_REGISTRY_IMAGE:migrator-stable --tag $CI_REGISTRY_IMAGE:migrator-stable --tag $CI_REGISTRY_IMAGE:migrator-$CI_COMMIT_SHA --tag $CI_REGISTRY_IMAGE:migrator-$CI_COMMIT_TAG -f Dockerfile.migrate .
        - echo "pushing built images to GitLab repository"
        - docker push $CI_REGISTRY_IMAGE:stable
        - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
        - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
        - docker push $CI_REGISTRY_IMAGE:migrator-stable
        - docker push $CI_REGISTRY_IMAGE:migrator-$CI_COMMIT_SHA
        - docker push $CI_REGISTRY_IMAGE:migrator-$CI_COMMIT_TAG
