= RateMyModule
Matthew Norton <matt@carrotmanmatt.com>
v1.2, 11/03/2024

ifndef::env-idea[]
include::.asciidoctorconfig[]
endif::[]

RateMyModule is a web application designed to enhance student feedback for university modules, providing a dynamic and user-friendly platform for honest reviews.

image:https://img.shields.io/badge/dynamic/toml?url=https%3A%2F%2Fraw.githubusercontent.com%2FCarrotManMatt%2FRateMyModule%2Fmain%2Fpyproject.toml&query=%24.tool.poetry.version&label=RateMyModule[Current Version,link={url-project-repo}]
image:https://img.shields.io/badge/Python-3.12-blue?&logo=Python&logoColor=white[Python Version,link={url-python-312}]
image:https://img.shields.io/badge/dynamic/toml?url=https%3A%2F%2Fraw.githubusercontent.com%2FCarrotManMatt%2FRateMyModule%2Fmain%2Fpoetry.lock&query=%24.package%5B%3F%28%40.name%3D%3D%27django%27%29%5D.version&logo=Django&label=Django[Django Version,link={url-django-home}]
image:https://git.cs.bham.ac.uk/team-projects-2023-24/team55/badges/main/pipeline.svg[Pipeline Status,link={url-project-main-branch}]


.This repository belongs to Group 55
[%collapsible%open]
====
- Delilah Lawes (dxl288@student.bham.ac.uk)
- Matthew Norton (mxn282@student.bham.ac.uk)
- Charles Wilson (cxw304@student.bham.ac.uk)
- Thomas Rose (txr244@student.bham.ac.uk)
- Ryan Bendall (rxb299@student.bham.ac.uk)
- Arthur Crymble (axc1277@student.bham.ac.uk)
====

== Development

A full guide on how to get started with developing in this repository is available in xref:dev_docs/start_here.adoc[`+start_here.adoc+`], within the link:dev_docs/[developer documentation].
