# Generated by Django 4.2.10 on 2024-02-29 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratemymodule', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='post',
            name='ensure_overall_rating_valid_choice',
        ),
        migrations.RemoveConstraint(
            model_name='post',
            name='ensure_difficulty_rating_valid_choice',
        ),
        migrations.RemoveConstraint(
            model_name='post',
            name='ensure_assessment_rating_valid_choice',
        ),
        migrations.RemoveConstraint(
            model_name='post',
            name='ensure_teaching_rating_valid_choice',
        ),
        migrations.AlterField(
            model_name='post',
            name='assessment_rating',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True, verbose_name='Assessment Rating'),
        ),
        migrations.AlterField(
            model_name='post',
            name='difficulty_rating',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True, verbose_name='Difficulty Rating'),
        ),
        migrations.AlterField(
            model_name='post',
            name='overall_rating',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Overall Rating'),
        ),
        migrations.AlterField(
            model_name='post',
            name='teaching_rating',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True, verbose_name='Teaching Rating'),
        ),
        migrations.AddConstraint(
            model_name='post',
            constraint=models.CheckConstraint(check=models.Q(('overall_rating__in', [1, 2, 3, 4, 5])), name='ensure_overall_rating_valid_choice'),
        ),
        migrations.AddConstraint(
            model_name='post',
            constraint=models.CheckConstraint(check=models.Q(('difficulty_rating__in', [1, 2, 3, 4, 5])), name='ensure_difficulty_rating_valid_choice'),
        ),
        migrations.AddConstraint(
            model_name='post',
            constraint=models.CheckConstraint(check=models.Q(('assessment_rating__in', [1, 2, 3, 4, 5])), name='ensure_assessment_rating_valid_choice'),
        ),
        migrations.AddConstraint(
            model_name='post',
            constraint=models.CheckConstraint(check=models.Q(('teaching_rating__in', [1, 2, 3, 4, 5])), name='ensure_teaching_rating_valid_choice'),
        ),
    ]
