# Generated by Django 4.2.10 on 2024-03-03 03:17

import django.core.validators
from django.db import migrations, models
import ratemymodule.models.validators


class Migration(migrations.Migration):

    dependencies = [
        ('ratemymodule', '0002_remove_post_ensure_overall_rating_valid_choice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='code',
            field=models.CharField(help_text='The unique reference code of this module within its university', max_length=60, validators=[django.core.validators.MinLengthValidator(2), ratemymodule.models.validators.UnicodePropertiesRegexValidator("\\A[\\p{L}0-9!?¿¡' &()-]+\\Z")], verbose_name='Reference Code'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'max_length': 'The Email Address must be at most 255 digits.', 'unique': 'A user with that Email Address already exists.'}, max_length=255, unique=True, validators=[ratemymodule.models.validators.HTML5EmailValidator(), ratemymodule.models.validators.FreeEmailValidator(), ratemymodule.models.validators.ConfusableEmailValidator(), ratemymodule.models.validators.ExampleEmailValidator()], verbose_name='Email Address'),
        ),
    ]
