# Generated by Django 4.2.10 on 2024-03-04 14:48

import django.core.validators
from django.db import migrations, models
import ratemymodule.models.validators


class Migration(migrations.Migration):

    dependencies = [
        ('ratemymodule', '0003_alter_module_code_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=60, validators=[django.core.validators.MinLengthValidator(3), ratemymodule.models.validators.UnicodePropertiesRegexValidator("\\A[\\p{L}\\p{N}!?¿¡' &()-]+\\Z")], verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='module',
            name='name',
            field=models.CharField(max_length=60, validators=[django.core.validators.MinLengthValidator(3), ratemymodule.models.validators.UnicodePropertiesRegexValidator("\\A[\\p{L}\\p{N}!?¿¡' &()-]+\\Z")], verbose_name='Name'),
        ),
    ]
