# Generated by Django 4.2.10 on 2024-03-04 16:06

import django.core.validators
from django.db import migrations, models
import ratemymodule.models.validators


class Migration(migrations.Migration):

    dependencies = [
        ('ratemymodule', '0004_alter_course_name_alter_module_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='othertag',
            name='name',
            field=models.CharField(max_length=60, unique=True, validators=[django.core.validators.MinLengthValidator(2), ratemymodule.models.validators.UnicodePropertiesRegexValidator("\\A[\\p{L}!?¿¡' +&()#-]+\\Z")], verbose_name='Tag Name'),
        ),
        migrations.AlterField(
            model_name='tooltag',
            name='name',
            field=models.CharField(max_length=60, unique=True, validators=[django.core.validators.MinLengthValidator(2), ratemymodule.models.validators.UnicodePropertiesRegexValidator("\\A[\\p{L}!?¿¡' +&()#-]+\\Z")], verbose_name='Tag Name'),
        ),
        migrations.AlterField(
            model_name='topictag',
            name='name',
            field=models.CharField(max_length=60, unique=True, validators=[django.core.validators.MinLengthValidator(2), ratemymodule.models.validators.UnicodePropertiesRegexValidator("\\A[\\p{L}!?¿¡' +&()#-]+\\Z")], verbose_name='Tag Name'),
        ),
    ]
